# worktree add - Create a new worktree

_worktree_add() {
    local BRANCH_NAME="$1"
    local FLAG="$2"

    if [ -z "$BRANCH_NAME" ]; then
        echo "Usage: worktree add <branch-name> [--setup]"
        return 1
    fi

    # Load project-specific config
    _worktree_load_project_config

    # Check if we're in a git repo
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        echo "Error: Not inside a git repository"
        return 1
    fi

    # Check if we're in the main repo, not a worktree
    if ! _worktree_is_main_repo; then
        echo "Error: You're inside a worktree, not the main repository."
        echo "Please run 'worktree add' from the main repository:"
        echo "  cd $(_worktree_get_main_repo)"
        return 1
    fi

    local CURRENT_DIR=$(basename "$(pwd)")
    local WORKTREE_PATH="../${CURRENT_DIR}-${BRANCH_NAME}"
    local MAIN_BRANCH
    local CURRENT_BRANCH

    # Determine the main branch (master or main)
    if git show-ref --verify --quiet refs/heads/main; then
        MAIN_BRANCH="main"
    elif git show-ref --verify --quiet refs/heads/master; then
        MAIN_BRANCH="master"
    else
        echo "Error: Could not find 'main' or 'master' branch"
        return 1
    fi

    # Check if we're on the main branch
    CURRENT_BRANCH=$(git branch --show-current)
    if [ "$CURRENT_BRANCH" != "$MAIN_BRANCH" ]; then
        echo "Switching to $MAIN_BRANCH branch..."
        git checkout "$MAIN_BRANCH" || return 1
    fi

    # Check if worktree path already exists
    if [ -d "$WORKTREE_PATH" ]; then
        echo "Error: Worktree path already exists: $WORKTREE_PATH"
        return 1
    fi

    # Create worktree with new or existing branch
    if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
        echo "Branch '$BRANCH_NAME' exists, checking it out..."
        git worktree add "$WORKTREE_PATH" "$BRANCH_NAME" || return 1
    else
        echo "Creating new branch '$BRANCH_NAME'..."
        git worktree add -b "$BRANCH_NAME" "$WORKTREE_PATH" || return 1
    fi

    # Symlink .key files from config/credentials (they're gitignored)
    local CREDENTIALS_DIR="config/credentials"
    if [ -d "$CREDENTIALS_DIR" ]; then
        for keyfile in "$CREDENTIALS_DIR"/*.key; do
            if [ -f "$keyfile" ]; then
                local keyfile_name=$(basename "$keyfile")
                local keyfile_abs=$(cd "$CREDENTIALS_DIR" && pwd)/"$keyfile_name"
                ln -s "$keyfile_abs" "$WORKTREE_PATH/$CREDENTIALS_DIR/$keyfile_name"
                echo "Symlinked: $keyfile_name"
            fi
        done
    fi

    # Symlink gitignored .env* files if configured
    if [ "$WORKTREE_SYMLINK_ENV_FILES" = "true" ]; then
        local MAIN_REPO_PATH=$(pwd)
        for envfile in .env*; do
            if [ -f "$envfile" ] && git check-ignore -q "$envfile" 2>/dev/null; then
                ln -s "$MAIN_REPO_PATH/$envfile" "$WORKTREE_PATH/$envfile"
                echo "Symlinked: $envfile"
            fi
        done
    fi

    # Copy Claude Code MCP server config if available
    local MAIN_REPO_ABS_PATH=$(pwd)
    local WORKTREE_ABS_PATH=$(cd "$WORKTREE_PATH" && pwd)
    _worktree_copy_claude_mcp_config "$MAIN_REPO_ABS_PATH" "$WORKTREE_ABS_PATH"

    # Create .overmind.env with port and DB config
    local SLOT=$(_worktree_get_slot "$WORKTREE_ABS_PATH")
    local RAILS_PORT=$((WORKTREE_BASE_RAILS_PORT + SLOT))
    local VITE_PORT=$((WORKTREE_BASE_VITE_PORT + SLOT))
    local SANITIZED_BRANCH=$(_worktree_sanitize_branch "$BRANCH_NAME")
    local DEV_DB="${WORKTREE_DEV_DB_PREFIX}_${SANITIZED_BRANCH}"
    local TEST_DB="${WORKTREE_TEST_DB_PREFIX}_${SANITIZED_BRANCH}"

    cat > "$WORKTREE_PATH/.overmind.env" << EOF
# Worktree-specific configuration (auto-generated by worktree add)
DB_NAME=$DEV_DB
TEST_DB_NAME=$TEST_DB
PORT=$RAILS_PORT
VITE_RUBY_PORT=$VITE_PORT
EOF

    # Create Procfile.local if template is provided
    if [ -n "$WORKTREE_PROCFILE_TEMPLATE" ]; then
        echo "$WORKTREE_PROCFILE_TEMPLATE" > "$WORKTREE_PATH/Procfile.local"
    fi

    echo ""
    echo "Worktree created at: $WORKTREE_PATH"
    echo "Branch: $BRANCH_NAME"
    echo "  Database: $DEV_DB"
    echo "  Test DB:  $TEST_DB"
    echo "  Rails port: $RAILS_PORT"
    echo "  Vite port: $VITE_PORT"

    if [ -z "$WORKTREE_PROCFILE_TEMPLATE" ]; then
        echo ""
        echo "Warning: WORKTREE_PROCFILE_TEMPLATE not set in .worktree.config"
        echo "You'll need to create Procfile.local manually before running 'worktree start'"
        echo "Use \${PORT} for Rails port and \${VITE_RUBY_PORT} for Vite port"
    fi

    # Change to the new worktree directory
    cd "$WORKTREE_PATH"

    # Run setup if --setup flag provided
    if [ "$FLAG" = "--setup" ]; then
        echo ""
        _worktree_setup
    else
        echo ""
        echo "Run 'worktree setup' to clone the dev database and install dependencies."
    fi
}
