# worktree adopt - Set up worktree-tool config for an existing git worktree

_worktree_adopt() {
    # Check if we're in a git repo
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        echo "Error: Not inside a git repository"
        return 1
    fi

    # Must be inside a worktree, not the main repo
    if _worktree_is_main_repo; then
        echo "Error: You're in the main repository, not a worktree."
        echo "Run this from inside a worktree created with 'git worktree add'."
        return 1
    fi

    local MAIN_REPO_ABS_PATH=$(_worktree_get_main_repo)
    local WORKTREE_ABS_PATH=$(pwd)
    local BRANCH_NAME=$(git branch --show-current)

    if [ -z "$BRANCH_NAME" ]; then
        echo "Error: Could not determine current branch"
        return 1
    fi

    # Load project-specific config (looks in main repo)
    _worktree_load_project_config

    # Skip if already adopted
    if [ -f ".overmind.env" ]; then
        echo "This worktree already has .overmind.env — it may have been adopted already."
        echo "Remove .overmind.env first if you want to re-adopt."
        return 1
    fi

    echo "Adopting worktree for branch '$BRANCH_NAME'..."
    echo "  Main repo: $MAIN_REPO_ABS_PATH"
    echo ""

    # Symlink .key files from config/credentials (they're gitignored)
    local CREDENTIALS_DIR="config/credentials"
    if [ -d "$MAIN_REPO_ABS_PATH/$CREDENTIALS_DIR" ]; then
        mkdir -p "$CREDENTIALS_DIR"
        for keyfile in "$MAIN_REPO_ABS_PATH/$CREDENTIALS_DIR"/*.key; do
            if [ -f "$keyfile" ]; then
                local keyfile_name=$(basename "$keyfile")
                if [ ! -e "$CREDENTIALS_DIR/$keyfile_name" ]; then
                    ln -s "$keyfile" "$CREDENTIALS_DIR/$keyfile_name"
                    echo "Symlinked: $CREDENTIALS_DIR/$keyfile_name"
                fi
            fi
        done
    fi

    # Symlink gitignored .env* files if configured
    if [ "$WORKTREE_SYMLINK_ENV_FILES" = "true" ]; then
        for envfile in "$MAIN_REPO_ABS_PATH"/.env*; do
            if [ -f "$envfile" ]; then
                local envfile_name=$(basename "$envfile")
                if [ ! -e "$envfile_name" ] && git -C "$MAIN_REPO_ABS_PATH" check-ignore -q "$envfile_name" 2>/dev/null; then
                    ln -s "$envfile" "$envfile_name"
                    echo "Symlinked: $envfile_name"
                fi
            fi
        done
    fi

    # Mirror .claude directory structure with symlinked files
    if [ -d "$MAIN_REPO_ABS_PATH/.claude" ]; then
        while IFS= read -r file; do
            local rel_dir=$(dirname "$file")
            if [ ! -e "$WORKTREE_ABS_PATH/$file" ]; then
                mkdir -p "$WORKTREE_ABS_PATH/$rel_dir"
                ln -s "$MAIN_REPO_ABS_PATH/$file" "$WORKTREE_ABS_PATH/$file"
                echo "Symlinked: $file"
            fi
        done < <(cd "$MAIN_REPO_ABS_PATH" && find .claude -type f)
    fi

    # Symlink configured paths from main repo to worktree
    if [ -n "$WORKTREE_SYMLINK_PATHS" ]; then
        for symlink_path in $WORKTREE_SYMLINK_PATHS; do
            if [ -e "$MAIN_REPO_ABS_PATH/$symlink_path" ]; then
                local parent_dir=$(dirname "$WORKTREE_ABS_PATH/$symlink_path")
                mkdir -p "$parent_dir"
                if [ -e "$WORKTREE_ABS_PATH/$symlink_path" ] && [ ! -L "$WORKTREE_ABS_PATH/$symlink_path" ]; then
                    rm -rf "$WORKTREE_ABS_PATH/$symlink_path"
                fi
                if [ ! -L "$WORKTREE_ABS_PATH/$symlink_path" ]; then
                    ln -s "$MAIN_REPO_ABS_PATH/$symlink_path" "$WORKTREE_ABS_PATH/$symlink_path"
                    echo "Symlinked: $symlink_path"
                fi
            fi
        done
    fi

    # Copy Claude Code MCP server config if available
    _worktree_copy_claude_mcp_config "$MAIN_REPO_ABS_PATH" "$WORKTREE_ABS_PATH"

    # Create .overmind.env with port and DB config
    local SLOT=$(_worktree_get_slot "$WORKTREE_ABS_PATH")
    local RAILS_PORT=$((WORKTREE_BASE_RAILS_PORT + SLOT))
    local VITE_PORT=$((WORKTREE_BASE_VITE_PORT + SLOT))
    local SANITIZED_BRANCH=$(_worktree_sanitize_branch "$BRANCH_NAME")
    local DEV_DB="${WORKTREE_DEV_DB_PREFIX}_${SANITIZED_BRANCH}"
    local TEST_DB="${WORKTREE_TEST_DB_PREFIX}_${SANITIZED_BRANCH}"

    cat > ".overmind.env" << EOF
# Worktree-specific configuration (auto-generated by worktree adopt)
DB_NAME=$DEV_DB
TEST_DB_NAME=$TEST_DB
PORT=$RAILS_PORT
VITE_RUBY_PORT=$VITE_PORT
EOF

    # Create Procfile.local if template is provided
    if [ -n "$WORKTREE_PROCFILE_TEMPLATE" ] && [ ! -f "Procfile.local" ]; then
        echo "$WORKTREE_PROCFILE_TEMPLATE" > "Procfile.local"
    fi

    echo ""
    echo "Worktree adopted!"
    echo "  Branch: $BRANCH_NAME"
    echo "  Database: $DEV_DB"
    echo "  Test DB:  $TEST_DB"
    echo "  Rails port: $RAILS_PORT"
    echo "  Vite port: $VITE_PORT"
    echo ""
    echo "Run 'worktree setup' to clone the dev database and install dependencies."
}
